# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: E is for Everything
email: eamoses@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a creator, a connector and I work as a software engineer in civic engagement. ðŸš€
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://eamoses.github.io/" # the base hostname & protocol for your site
twitter_username: emilyannemoses
github_username:  eamoses
instagram_username: emilyannemoses

# Build settings
markdown: kramdown
